# Generated by Django 5.2 on 2025-04-18 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
        ('productos', '0004_notaventa_registronotaventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_aplicado', models.BooleanField(default=False)),
                ('finalizada', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ia.conversacioncliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'unique_together': {('conversacion', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='conversacioncliente',
            name='productos',
            field=models.ManyToManyField(through='ia.ProductoConversacion', to='productos.producto'),
        ),
    ]
