# Generated by Django 5.2 on 2025-04-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_conversacioncliente_productoconversacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversacioncliente',
            old_name='total',
            new_name='total_acumulado',
        ),
        migrations.RemoveField(
            model_name='conversacioncliente',
            name='creada',
        ),
        migrations.RemoveField(
            model_name='conversacioncliente',
            name='productos',
        ),
    ]
